name: chordflow_piano
description: ChordFlow Piano - beautiful chords and chord progressions.
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
      audioplayers: ^6.5.0

flutter:
  uses-material-design: true
